[build]
  publish = "dist"
  command = "echo 'Build already completed - using dist folder'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
